language: ruby
rvm:
- 2.1.3
bundler_args: "--without development production autotest"
services:
- mongodb
- redis-server
before_install:
- wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.13.deb
- sudo dpkg --purge elasticsearch
- sudo dpkg -i elasticsearch-0.90.13.deb
- sudo service elasticsearch start
- gem update --system
- travis_retry gem install bundler --pre
before_script:
- cp -f config/database.travis.yml config/database.yml
- cp -f .env.example .env
- bundle exec rake db:create:all
- bundle exec rake db:schema:load
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
env:
  global:
    secure: X7TELzrdZJg8lph9n392igWcUfzWpNUb0wrYvKRIOj1Uz+vT9xrAdv8txJgA/HWwby7gNR3IOcoa3CamxyGCstBnrzKu/xKxk9BYpp5BSfSTLeKrTZf7X45kWc2w70VpgrYUgCmfT1xQxuC7WIgUeqiF7zn7XWogpv8jy6JrFC0=
